[2025-02-14T06:26:44.429+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T06:26:44.515+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline_dag.run_etl_pipeline manual__2025-02-14T06:26:42.716178+00:00 [queued]>
[2025-02-14T06:26:44.555+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline_dag.run_etl_pipeline manual__2025-02-14T06:26:42.716178+00:00 [queued]>
[2025-02-14T06:26:44.557+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-14T06:26:44.585+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): run_etl_pipeline> on 2025-02-14 06:26:42.716178+00:00
[2025-02-14T06:26:44.615+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=208) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-14T06:26:44.613+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_dag', 'run_etl_pipeline', 'manual__2025-02-14T06:26:42.716178+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_dag.py', '--cfg-path', '/tmp/tmpydlrqqvw']
[2025-02-14T06:26:44.629+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask run_etl_pipeline
[2025-02-14T06:26:44.621+0000] {standard_task_runner.py:72} INFO - Started process 214 to run task
[2025-02-14T06:26:44.757+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline_dag.run_etl_pipeline manual__2025-02-14T06:26:42.716178+00:00 [running]> on host eb31e5c80e52
[2025-02-14T06:26:45.022+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline_dag' AIRFLOW_CTX_TASK_ID='run_etl_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T06:26:42.716178+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T06:26:42.716178+00:00'
[2025-02-14T06:26:45.024+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-14T06:26:45.071+0000] {logging_mixin.py:190} INFO - Starting ETL pipeline...
[2025-02-14T06:26:45.073+0000] {logging_mixin.py:190} INFO - Extracting data...
[2025-02-14T06:29:42.146+0000] {logging_mixin.py:190} INFO - Detected file encoding: ISO-8859-1
[2025-02-14T06:29:42.886+0000] {logging_mixin.py:190} INFO - CSV 파일 컬럼: ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']
[2025-02-14T06:29:42.888+0000] {logging_mixin.py:190} INFO - 데이터 샘플:
[2025-02-14T06:29:42.929+0000] {logging_mixin.py:190} INFO -    InvoiceNo StockCode  ... CustomerID         Country
0    536365    85123A  ...    17850.0  United Kingdom
1    536365     71053  ...    17850.0  United Kingdom
2    536365    84406B  ...    17850.0  United Kingdom
3    536365    84029G  ...    17850.0  United Kingdom
4    536365    84029E  ...    17850.0  United Kingdom

[5 rows x 8 columns]
[2025-02-14T06:29:42.929+0000] {logging_mixin.py:190} INFO - Data extracted successfully!
[2025-02-14T06:29:42.930+0000] {logging_mixin.py:190} INFO - Transforming data...
[2025-02-14T06:29:42.930+0000] {logging_mixin.py:190} INFO - 변환 전 컬럼: ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']
[2025-02-14T06:29:43.219+0000] {logging_mixin.py:190} INFO - Data transformed successfully!
[2025-02-14T06:29:43.220+0000] {logging_mixin.py:190} INFO - Loading data...
[2025-02-14T06:29:50.282+0000] {logging_mixin.py:190} INFO - Data loading failed: (psycopg2.errors.UndefinedColumn) column "Country" of relation "sales" does not exist
LINE 1: ...product_name, quantity, date, price, customer_id, "Country",...
                                                             ^

[SQL: INSERT INTO sales (invoice_no, stock_code, product_name, quantity, date, price, customer_id, "Country", total_amount) VALUES (%(invoice_no)s, %(stock_code)s, %(product_name)s, %(quantity)s, %(date)s, %(price)s, %(customer_id)s, %(Country)s, %(total_amount)s)]
[parameters: ({'invoice_no': '536365', 'stock_code': '85123A', 'product_name': 'WHITE HANGING HEART T-LIGHT HOLDER', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 2.55, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 15.299999999999999}, {'invoice_no': '536365', 'stock_code': '71053', 'product_name': 'WHITE METAL LANTERN', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '84406B', 'product_name': 'CREAM CUPID HEARTS COAT HANGER', 'quantity': 8, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 2.75, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 22.0}, {'invoice_no': '536365', 'stock_code': '84029G', 'product_name': 'KNITTED UNION FLAG HOT WATER BOTTLE', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '84029E', 'product_name': 'RED WOOLLY HOTTIE WHITE HEART.', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '22752', 'product_name': 'SET 7 BABUSHKA NESTING BOXES', 'quantity': 2, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 7.65, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 15.3}, {'invoice_no': '536365', 'stock_code': '21730', 'product_name': 'GLASS STAR FROSTED T-LIGHT HOLDER', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 4.25, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 25.5}, {'invoice_no': '536366', 'stock_code': '22633', 'product_name': 'HAND WARMER UNION JACK', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 28), 'price': 1.85, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 11.100000000000001}  ... displaying 10 of 541909 total bound parameter sets ...  {'invoice_no': '581587', 'stock_code': '23255', 'product_name': 'CHILDRENS CUTLERY CIRCUS PARADE', 'quantity': 4, 'date': datetime.datetime(2011, 12, 9, 12, 50), 'price': 4.15, 'customer_id': 12680.0, 'Country': 'France', 'total_amount': 16.6}, {'invoice_no': '581587', 'stock_code': '22138', 'product_name': 'BAKING SET 9 PIECE RETROSPOT ', 'quantity': 3, 'date': datetime.datetime(2011, 12, 9, 12, 50), 'price': 4.95, 'customer_id': 12680.0, 'Country': 'France', 'total_amount': 14.850000000000001})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-02-14T06:29:50.283+0000] {logging_mixin.py:190} INFO - ETL pipeline failed: (psycopg2.errors.UndefinedColumn) column "Country" of relation "sales" does not exist
LINE 1: ...product_name, quantity, date, price, customer_id, "Country",...
                                                             ^

[SQL: INSERT INTO sales (invoice_no, stock_code, product_name, quantity, date, price, customer_id, "Country", total_amount) VALUES (%(invoice_no)s, %(stock_code)s, %(product_name)s, %(quantity)s, %(date)s, %(price)s, %(customer_id)s, %(Country)s, %(total_amount)s)]
[parameters: ({'invoice_no': '536365', 'stock_code': '85123A', 'product_name': 'WHITE HANGING HEART T-LIGHT HOLDER', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 2.55, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 15.299999999999999}, {'invoice_no': '536365', 'stock_code': '71053', 'product_name': 'WHITE METAL LANTERN', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '84406B', 'product_name': 'CREAM CUPID HEARTS COAT HANGER', 'quantity': 8, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 2.75, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 22.0}, {'invoice_no': '536365', 'stock_code': '84029G', 'product_name': 'KNITTED UNION FLAG HOT WATER BOTTLE', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '84029E', 'product_name': 'RED WOOLLY HOTTIE WHITE HEART.', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '22752', 'product_name': 'SET 7 BABUSHKA NESTING BOXES', 'quantity': 2, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 7.65, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 15.3}, {'invoice_no': '536365', 'stock_code': '21730', 'product_name': 'GLASS STAR FROSTED T-LIGHT HOLDER', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 4.25, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 25.5}, {'invoice_no': '536366', 'stock_code': '22633', 'product_name': 'HAND WARMER UNION JACK', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 28), 'price': 1.85, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 11.100000000000001}  ... displaying 10 of 541909 total bound parameter sets ...  {'invoice_no': '581587', 'stock_code': '23255', 'product_name': 'CHILDRENS CUTLERY CIRCUS PARADE', 'quantity': 4, 'date': datetime.datetime(2011, 12, 9, 12, 50), 'price': 4.15, 'customer_id': 12680.0, 'Country': 'France', 'total_amount': 16.6}, {'invoice_no': '581587', 'stock_code': '22138', 'product_name': 'BAKING SET 9 PIECE RETROSPOT ', 'quantity': 3, 'date': datetime.datetime(2011, 12, 9, 12, 50), 'price': 4.95, 'customer_id': 12680.0, 'Country': 'France', 'total_amount': 14.850000000000001})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-02-14T06:29:50.284+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "Country" of relation "sales" does not exist
LINE 1: ...product_name, quantity, date, price, customer_id, "Country",...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/etl_pipeline.py", line 124, in run_etl_script
    load_data(transformed_data, customer_summary, engine)
  File "/opt/airflow/scripts/etl_pipeline.py", line 98, in load_data
    df.to_sql('sales', engine, if_exists='append', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "Country" of relation "sales" does not exist
LINE 1: ...product_name, quantity, date, price, customer_id, "Country",...
                                                             ^

[SQL: INSERT INTO sales (invoice_no, stock_code, product_name, quantity, date, price, customer_id, "Country", total_amount) VALUES (%(invoice_no)s, %(stock_code)s, %(product_name)s, %(quantity)s, %(date)s, %(price)s, %(customer_id)s, %(Country)s, %(total_amount)s)]
[parameters: ({'invoice_no': '536365', 'stock_code': '85123A', 'product_name': 'WHITE HANGING HEART T-LIGHT HOLDER', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 2.55, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 15.299999999999999}, {'invoice_no': '536365', 'stock_code': '71053', 'product_name': 'WHITE METAL LANTERN', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '84406B', 'product_name': 'CREAM CUPID HEARTS COAT HANGER', 'quantity': 8, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 2.75, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 22.0}, {'invoice_no': '536365', 'stock_code': '84029G', 'product_name': 'KNITTED UNION FLAG HOT WATER BOTTLE', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '84029E', 'product_name': 'RED WOOLLY HOTTIE WHITE HEART.', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '22752', 'product_name': 'SET 7 BABUSHKA NESTING BOXES', 'quantity': 2, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 7.65, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 15.3}, {'invoice_no': '536365', 'stock_code': '21730', 'product_name': 'GLASS STAR FROSTED T-LIGHT HOLDER', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 4.25, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 25.5}, {'invoice_no': '536366', 'stock_code': '22633', 'product_name': 'HAND WARMER UNION JACK', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 28), 'price': 1.85, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 11.100000000000001}  ... displaying 10 of 541909 total bound parameter sets ...  {'invoice_no': '581587', 'stock_code': '23255', 'product_name': 'CHILDRENS CUTLERY CIRCUS PARADE', 'quantity': 4, 'date': datetime.datetime(2011, 12, 9, 12, 50), 'price': 4.15, 'customer_id': 12680.0, 'Country': 'France', 'total_amount': 16.6}, {'invoice_no': '581587', 'stock_code': '22138', 'product_name': 'BAKING SET 9 PIECE RETROSPOT ', 'quantity': 3, 'date': datetime.datetime(2011, 12, 9, 12, 50), 'price': 4.95, 'customer_id': 12680.0, 'Country': 'France', 'total_amount': 14.850000000000001})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-02-14T06:29:50.361+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline_dag, task_id=run_etl_pipeline, run_id=manual__2025-02-14T06:26:42.716178+00:00, execution_date=20250214T062642, start_date=20250214T062644, end_date=20250214T062950
[2025-02-14T06:29:50.403+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-14T06:29:50.404+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2 for task run_etl_pipeline ((psycopg2.errors.UndefinedColumn) column "Country" of relation "sales" does not exist
LINE 1: ...product_name, quantity, date, price, customer_id, "Country",...
                                                             ^

[SQL: INSERT INTO sales (invoice_no, stock_code, product_name, quantity, date, price, customer_id, "Country", total_amount) VALUES (%(invoice_no)s, %(stock_code)s, %(product_name)s, %(quantity)s, %(date)s, %(price)s, %(customer_id)s, %(Country)s, %(total_amount)s)]
[parameters: ({'invoice_no': '536365', 'stock_code': '85123A', 'product_name': 'WHITE HANGING HEART T-LIGHT HOLDER', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 2.55, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 15.299999999999999}, {'invoice_no': '536365', 'stock_code': '71053', 'product_name': 'WHITE METAL LANTERN', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '84406B', 'product_name': 'CREAM CUPID HEARTS COAT HANGER', 'quantity': 8, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 2.75, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 22.0}, {'invoice_no': '536365', 'stock_code': '84029G', 'product_name': 'KNITTED UNION FLAG HOT WATER BOTTLE', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '84029E', 'product_name': 'RED WOOLLY HOTTIE WHITE HEART.', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '22752', 'product_name': 'SET 7 BABUSHKA NESTING BOXES', 'quantity': 2, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 7.65, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 15.3}, {'invoice_no': '536365', 'stock_code': '21730', 'product_name': 'GLASS STAR FROSTED T-LIGHT HOLDER', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 4.25, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 25.5}, {'invoice_no': '536366', 'stock_code': '22633', 'product_name': 'HAND WARMER UNION JACK', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 28), 'price': 1.85, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 11.100000000000001}  ... displaying 10 of 541909 total bound parameter sets ...  {'invoice_no': '581587', 'stock_code': '23255', 'product_name': 'CHILDRENS CUTLERY CIRCUS PARADE', 'quantity': 4, 'date': datetime.datetime(2011, 12, 9, 12, 50), 'price': 4.15, 'customer_id': 12680.0, 'Country': 'France', 'total_amount': 16.6}, {'invoice_no': '581587', 'stock_code': '22138', 'product_name': 'BAKING SET 9 PIECE RETROSPOT ', 'quantity': 3, 'date': datetime.datetime(2011, 12, 9, 12, 50), 'price': 4.95, 'customer_id': 12680.0, 'Country': 'France', 'total_amount': 14.850000000000001})]
(Background on this error at: https://sqlalche.me/e/14/f405); 214)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "Country" of relation "sales" does not exist
LINE 1: ...product_name, quantity, date, price, customer_id, "Country",...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/scripts/etl_pipeline.py", line 124, in run_etl_script
    load_data(transformed_data, customer_summary, engine)
  File "/opt/airflow/scripts/etl_pipeline.py", line 98, in load_data
    df.to_sql('sales', engine, if_exists='append', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "Country" of relation "sales" does not exist
LINE 1: ...product_name, quantity, date, price, customer_id, "Country",...
                                                             ^

[SQL: INSERT INTO sales (invoice_no, stock_code, product_name, quantity, date, price, customer_id, "Country", total_amount) VALUES (%(invoice_no)s, %(stock_code)s, %(product_name)s, %(quantity)s, %(date)s, %(price)s, %(customer_id)s, %(Country)s, %(total_amount)s)]
[parameters: ({'invoice_no': '536365', 'stock_code': '85123A', 'product_name': 'WHITE HANGING HEART T-LIGHT HOLDER', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 2.55, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 15.299999999999999}, {'invoice_no': '536365', 'stock_code': '71053', 'product_name': 'WHITE METAL LANTERN', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '84406B', 'product_name': 'CREAM CUPID HEARTS COAT HANGER', 'quantity': 8, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 2.75, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 22.0}, {'invoice_no': '536365', 'stock_code': '84029G', 'product_name': 'KNITTED UNION FLAG HOT WATER BOTTLE', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '84029E', 'product_name': 'RED WOOLLY HOTTIE WHITE HEART.', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 3.39, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 20.34}, {'invoice_no': '536365', 'stock_code': '22752', 'product_name': 'SET 7 BABUSHKA NESTING BOXES', 'quantity': 2, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 7.65, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 15.3}, {'invoice_no': '536365', 'stock_code': '21730', 'product_name': 'GLASS STAR FROSTED T-LIGHT HOLDER', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 26), 'price': 4.25, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 25.5}, {'invoice_no': '536366', 'stock_code': '22633', 'product_name': 'HAND WARMER UNION JACK', 'quantity': 6, 'date': datetime.datetime(2010, 12, 1, 8, 28), 'price': 1.85, 'customer_id': 17850.0, 'Country': 'United Kingdom', 'total_amount': 11.100000000000001}  ... displaying 10 of 541909 total bound parameter sets ...  {'invoice_no': '581587', 'stock_code': '23255', 'product_name': 'CHILDRENS CUTLERY CIRCUS PARADE', 'quantity': 4, 'date': datetime.datetime(2011, 12, 9, 12, 50), 'price': 4.15, 'customer_id': 12680.0, 'Country': 'France', 'total_amount': 16.6}, {'invoice_no': '581587', 'stock_code': '22138', 'product_name': 'BAKING SET 9 PIECE RETROSPOT ', 'quantity': 3, 'date': datetime.datetime(2011, 12, 9, 12, 50), 'price': 4.95, 'customer_id': 12680.0, 'Country': 'France', 'total_amount': 14.850000000000001})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-02-14T06:29:50.526+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-14T06:29:50.569+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-14T06:29:50.570+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
